main: me.stomper.btools.Main
name: btools
description: lightweight admin tools
version: 0.1.1-01
author: stomper387
api-version: 1.19
website: www.github.com/stomper387/btools

commands:
  ban:
    description: Bans any player. (REASON/TIME still in development)
  kick:
    description: Kick any player.
  gamemode:
    description: Change any players gamemode.
  echest:
    description: Opens Ender Chest.
  fly:
    description: A toggle fly command.
  gmc:
    description: A shortcut to enter Creative.
  gms:
    description: A shortcut to enter Survival.
  heal:
    description: Heal and Feed yourself.
  broadcast:
    description: Broadcast a message to the server.
  g:
    description: Bless yourself.
